### ISSUE TITLE
License

### ISSUE THREAD

**Issue by irabinovitch** [remind101/dnsdog#1]
Hello,

First off I wanted to thank you for building this great tool.  I'd like to link to it from the Datadog libraries and integrations documentation.  When you have a moment can you confirm which license you are releasing this code under? 
Thanks!

**Comment by ejholmes** [comment]
Hi @irabinovitch. I've added a BSD-2 license. Thanks!

**Comment by irabinovitch** [comment]
Thanks @ejholmes!
